services:
  standalone-firefox:
    container_name: standalone-firefox
    image: 'selenium/standalone-firefox:4.36.0-20251001'
    shm_size: 2g
    environment:
      SE_NODE_SESSION_TIMEOUT: 60
      SE_NODE_MAX_SESSION_IDLE_TIME: 60
      VNC_NO_PASSWORD: 'true'  # optionnel, pour VNC sans mot de passe
    networks:
      - selenium-network
    ports:
      - 4444:4444  # Selenium
      - '7900:7900'  # VNC (optionnel)
    restart: unless-stopped  # optionnel, pour relancer si crash
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api-alcuin-calendar:
    build: .
    depends_on:
      standalone-firefox:
        condition: service_healthy
    networks:
        - selenium-network
    environment:
      # exemple : URL de Selenium accessible depuis Python
      SELENIUM_URL: http://standalone-firefox:4444/wd/hub
    ports:
      - 5000:5000  # exposer le port de ton API si besoin
    volumes:
      - ./Logs:/app/Logs     # pour persister les logs hors du container
      - ./Secrets:/app/Secrets  # pour tes fichiers secrets
      - ./Calendars:/app/Calendars  # pour tes fichiers de calendrier
    #command: ["uv", "run", "main"]  # ou ton CMD par défaut dans Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  Secrets:

networks:
  selenium-network: