[project]
name = "apialcuincalendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.116.1",
    "selenium>=4.35.0",
    "uvicorn>=0.35.0",
]
